blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/m-oonn/YOLO/tree/main/docs
    about: Read the docs first.
  - name: 💬 GitHub Discussions
    url: https://github.com/m-oonn/YOLO/discussions
    about: Ask questions and discuss with the community.
