# Copyright (c) 2025 YOLO Course Design Contributors
# SPDX-License-Identifier: Apache-2.0

"""Shared data models for the detection and rules engine.

Canonical definitions of Detection and Event dataclasses used across
the rules engine, enhanced rules engine, pipeline, alarm engine, and
event storage. Merged from previously duplicated copies in rules.py
and enhanced_rules.py.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .geometry import bbox_aspect_h_over_w


@dataclass
class Detection:
    """A single detection result from YOLO."""

    track_id: int | None
    class_id: int
    conf: float
    x1: float
    y1: float
    x2: float
    y2: float

    @property
    def cx(self) -> float:
        return (self.x1 + self.x2) / 2.0

    @property
    def cy(self) -> float:
        return (self.y1 + self.y2) / 2.0

    @property
    def width(self) -> float:
        return self.x2 - self.x1

    @property
    def height(self) -> float:
        return self.y2 - self.y1

    @property
    def name(self) -> str:
        from core.constants import get_class_name

        return get_class_name(self.class_id)

    @property
    def aspect_h_over_w(self) -> float:
        return bbox_aspect_h_over_w(self.x1, self.y1, self.x2, self.y2)

    @property
    def area(self) -> float:
        return self.width * self.height


@dataclass
class Event:
    """An event generated by the rules engine."""

    event_type: str
    timestamp_s: float
    frame_index: int
    track_id: int | None = None
    zone_name: str | None = None
    confidence: float | None = None
    bbox: dict[str, float] | None = None
    extra: dict[str, Any] = field(default_factory=dict)
    description: str = ""
    source: str | None = None
