# Copyright (c) 2025 YOLO Course Design Contributors
# SPDX-License-Identifier: MIT

"""Rules engine for behavior detection from YOLO detections.

Supports: running, falling, crowd detection, intrusion, and fight detection.
Each rule is independently configurable via the YAML configuration.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from typing import Any

from .config import AppConfig
from .geometry import bbox_aspect_h_over_w, point_in_polygon


@dataclass
class Detection:
    """A single detection result from YOLO."""
    track_id: int | None
    class_id: int
    conf: float
    x1: float
    y1: float
    x2: float
    y2: float

    @property
    def cx(self) -> float:
        return (self.x1 + self.x2) / 2.0

    @property
    def cy(self) -> float:
        return (self.y1 + self.y2) / 2.0

    @property
    def aspect_h_over_w(self) -> float:
        return bbox_aspect_h_over_w(self.x1, self.y1, self.x2, self.y2)


@dataclass
class Event:
    """An event generated by the rules engine."""
    event_type: str
    timestamp_s: float
    frame_index: int
    track_id: int | None = None
    zone_name: str | None = None
    confidence: float | None = None
    bbox: dict[str, float] | None = None
    extra: dict[str, Any] = field(default_factory=dict)
    description: str = ""


class RulesEngine:
    """Applies behavior detection rules to a stream of detections."""

    def __init__(self, cfg: AppConfig, person_class_id: int = 0):
        self.cfg = cfg
        self.person_class_id = person_class_id

        # Track history buffers
        self._pos_hist: dict[int, deque[tuple[float, float, float]]] = {}
        self._aspect_hist: dict[int, deque[tuple[float, float]]] = {}

        # Running detection state
        self._running_start: dict[int, float | None] = {}
        self._running_last_emit: dict[int, float] = {}

        # Fall detection state
        self._fall_last_emit: dict[int, float] = {}

        # Intrusion detection state
        self._intrusion_inside: dict[tuple[int, str], bool] = {}
        self._intrusion_last_emit: dict[tuple[int, str], float] = {}

        # Crowd detection state
        self._crowd_last_emit: float = -1e18

        # Fight detection state
        self._fight_start: dict[tuple[int, int], float | None] = {}
        self._fight_last_emit: dict[tuple[int, int], float] = {}

        # Fallback track ID management (when ByteTrack IDs are unavailable)
        self._next_fallback_id: int = 1
        self._prev_fallback_dets: list[tuple[Detection, int]] = []

    def _make_event(
        self, event_type: str, t: float, frame_index: int,
        track_id: int | None = None, zone_name: str | None = None,
        conf: float | None = None, bbox: dict[str, float] | None = None,
        extra: dict[str, Any] | None = None
    ) -> Event:
        parts = [event_type]
        if zone_name:
            parts.append(f"in zone {zone_name}")
        if track_id is not None:
            parts.append(f"(track {track_id})")
        return Event(
            event_type=event_type,
            timestamp_s=t,
            frame_index=frame_index,
            track_id=track_id,
            zone_name=zone_name,
            confidence=conf,
            bbox=bbox,
            extra=extra or {},
            description=" ".join(parts),
        )

    @staticmethod
    def _iou(a: Detection, b: Detection) -> float:
        """Compute Intersection-over-Union of two bounding boxes."""
        x1 = max(a.x1, b.x1)
        y1 = max(a.y1, b.y1)
        x2 = min(a.x2, b.x2)
        y2 = min(a.y2, b.y2)
        inter = max(0, x2 - x1) * max(0, y2 - y1)
        area_a = max(1e-6, (a.x2 - a.x1) * (a.y2 - a.y1))
        area_b = max(1e-6, (b.x2 - b.x1) * (b.y2 - b.y1))
        return inter / (area_a + area_b - inter)

    def _resolve_tid(self, d: Detection) -> int:
        """Resolve track ID, using IOU matching as fallback when ByteTrack ID is absent."""
        if d.track_id is not None:
            return int(d.track_id)

        best_iou = 0.3
        best_id = None
        for prev_d, fid in self._prev_fallback_dets:
            iou = self._iou(d, prev_d)
            if iou > best_iou:
                best_iou = iou
                best_id = fid

        if best_id is not None:
            return best_id

        fid = self._next_fallback_id
        self._next_fallback_id += 1
        return fid

    def update(self, detections: list[Detection], frame_index: int, timestamp_s: float) -> list[Event]:
        """Process new detections and return any triggered events."""
        events: list[Event] = []
        persons = [d for d in detections if d.class_id == self.person_class_id]

        # Update history for all person detections
        for d in persons:
            tid = self._resolve_tid(d)
            self._pos_hist.setdefault(tid, deque(maxlen=120)).append((timestamp_s, d.cx, d.cy))
            self._aspect_hist.setdefault(tid, deque(maxlen=120)).append((timestamp_s, d.aspect_h_over_w))

        # Apply each enabled rule
        if self.cfg.rules.running.enabled:
            events.extend(self._detect_running(persons, timestamp_s, frame_index))
        if self.cfg.rules.fall.enabled:
            events.extend(self._detect_fall(persons, timestamp_s, frame_index))
        if self.cfg.rules.crowd.enabled:
            events.extend(self._detect_crowd(persons, timestamp_s, frame_index))
        if self.cfg.rules.intrusion.enabled:
            events.extend(self._detect_intrusion(persons, timestamp_s, frame_index))
        if self.cfg.rules.fight.enabled:
            events.extend(self._detect_fight(persons, timestamp_s, frame_index))

        # Save untracked person detections for next frame's IOU matching
        self._prev_fallback_dets = [
            (d, self._resolve_tid(d)) for d in persons
            if d.track_id is None
        ]

        return events

    def _detect_running(self, persons: list[Detection], t: float, frame_idx: int) -> list[Event]:
        events = []
        for d in persons:
            tid = self._resolve_tid(d)
            hist = self._pos_hist.get(tid)
            if not hist or len(hist) < 2:
                continue

            _, cx_prev, cy_prev = hist[-2]
            _, cx_now, cy_now = hist[-1]
            dt = max(1e-6, t - hist[-2][0])
            speed = ((cx_now - cx_prev) ** 2 + (cy_now - cy_prev) ** 2) ** 0.5 / dt

            if speed >= self.cfg.rules.running.speed_px_s:
                start = self._running_start.get(tid)
                if start is None:
                    self._running_start[tid] = t
                    continue
                if (t - start) >= self.cfg.rules.running.min_duration_s:
                    last_emit = self._running_last_emit.get(tid, -1e18)
                    if (t - last_emit) >= self.cfg.rules.running.debounce_s:
                        bbox = {"x1": d.x1, "y1": d.y1, "x2": d.x2, "y2": d.y2}
                        events.append(self._make_event(
                            "running", t, frame_idx, tid, conf=d.conf, bbox=bbox,
                            extra={"speed_px_s": float(speed)}))
                        self._running_last_emit[tid] = t
                    self._running_start[tid] = None
            else:
                self._running_start[tid] = None
        return events

    def _detect_fall(self, persons: list[Detection], t: float, frame_idx: int) -> list[Event]:
        events = []
        win = self.cfg.rules.fall.transition_window_s
        for d in persons:
            tid = self._resolve_tid(d)
            hist = self._aspect_hist.get(tid)
            if not hist or len(hist) < 2:
                continue

            last_emit = self._fall_last_emit.get(tid, -1e18)
            if (t - last_emit) < self.cfg.rules.fall.debounce_s:
                continue

            t_min = t - win
            upright_seen = any(
                aspect >= self.cfg.rules.fall.upright_aspect_min
                for ts, aspect in hist if ts >= t_min
            )
            fallen_seen = upright_seen and any(
                aspect <= self.cfg.rules.fall.fallen_aspect_max
                for ts, aspect in hist if ts >= t_min
            )

            if upright_seen and fallen_seen:
                bbox = {"x1": d.x1, "y1": d.y1, "x2": d.x2, "y2": d.y2}
                events.append(self._make_event(
                    "fall", t, frame_idx, tid, conf=d.conf, bbox=bbox,
                    extra={"aspect_h_over_w": float(d.aspect_h_over_w)}))
                self._fall_last_emit[tid] = t
        return events

    def _detect_crowd(self, persons: list[Detection], t: float, frame_idx: int) -> list[Event]:
        events = []
        if len(persons) < 2:
            return events
        proximity = self.cfg.rules.crowd.proximity_px
        # Spatial clustering: connect people within proximity_px of each other
        tracked = [(self._resolve_tid(p), p.cx, p.cy) for p in persons]
        n = len(tracked)
        visited = [False] * n
        max_cluster = 0
        for i in range(n):
            if visited[i]:
                continue
            cluster = 0
            stack = [i]
            visited[i] = True
            while stack:
                idx = stack.pop()
                cluster += 1
                _, cx_i, cy_i = tracked[idx]
                for j in range(n):
                    if visited[j]:
                        continue
                    _, cx_j, cy_j = tracked[j]
                    dist = ((cx_i - cx_j) ** 2 + (cy_i - cy_j) ** 2) ** 0.5
                    if dist <= proximity:
                        visited[j] = True
                        stack.append(j)
            max_cluster = max(max_cluster, cluster)
        if max_cluster >= self.cfg.rules.crowd.min_people and (t - self._crowd_last_emit) >= self.cfg.rules.crowd.debounce_s:
            self._crowd_last_emit = t
            events.append(self._make_event(
                "crowd", t, frame_idx, extra={"people_count": max_cluster}))
        return events

    def _detect_intrusion(self, persons: list[Detection], t: float, frame_idx: int) -> list[Event]:
        events = []
        for zone in self.cfg.rules.intrusion.zones:
            for d in persons:
                tid = self._resolve_tid(d)
                inside = point_in_polygon(d.cx, d.cy, zone.polygon)
                key = (tid, zone.name)
                if inside and not self._intrusion_inside.get(key, False):
                    last_emit = self._intrusion_last_emit.get(key, -1e18)
                    if (t - last_emit) >= self.cfg.rules.intrusion.debounce_s:
                        bbox = {"x1": d.x1, "y1": d.y1, "x2": d.x2, "y2": d.y2}
                        events.append(self._make_event(
                            "intrusion", t, frame_idx, tid, zone_name=zone.name,
                            conf=d.conf, bbox=bbox))
                        self._intrusion_last_emit[key] = t
                self._intrusion_inside[key] = inside
        return events

    def _detect_fight(self, persons: list[Detection], t: float, frame_idx: int) -> list[Event]:
        events = []
        valid = []
        for d in persons:
            tid = self._resolve_tid(d)
            if len(self._pos_hist.get(tid, [])) >= 2:
                valid.append((tid, d))

        for i in range(len(valid)):
            for j in range(i + 1, len(valid)):
                tid1, d1 = valid[i]
                tid2, d2 = valid[j]
                key = tuple(sorted([tid1, tid2]))
                distance = ((d1.cx - d2.cx) ** 2 + (d1.cy - d2.cy) ** 2) ** 0.5

                if distance <= self.cfg.rules.fight.distance_threshold:
                    speed1 = self._calc_speed(tid1)
                    speed2 = self._calc_speed(tid2)
                    if speed1 >= self.cfg.rules.fight.movement_threshold or speed2 >= self.cfg.rules.fight.movement_threshold:
                        start = self._fight_start.get(key)
                        if start is None:
                            self._fight_start[key] = t
                            continue
                        if (t - start) >= self.cfg.rules.fight.min_duration_s:
                            last_emit = self._fight_last_emit.get(key, -1e18)
                            if (t - last_emit) >= self.cfg.rules.fight.debounce_s:
                                bbox = {
                                    "x1": min(d1.x1, d2.x1), "y1": min(d1.y1, d2.y1),
                                    "x2": max(d1.x2, d2.x2), "y2": max(d1.y2, d2.y2),
                                }
                                events.append(self._make_event(
                                    "fight", t, frame_idx, conf=(d1.conf + d2.conf) / 2, bbox=bbox,
                                    extra={"track_ids": [tid1, tid2], "distance": float(distance),
                                           "speeds": [float(speed1), float(speed2)]}))
                                self._fight_last_emit[key] = t
                            self._fight_start[key] = None
                    else:
                        self._fight_start[key] = None
                else:
                    self._fight_start[key] = None
        return events

    def _calc_speed(self, tid: int) -> float:
        hist = self._pos_hist.get(tid)
        if not hist or len(hist) < 2:
            return 0.0
        t_prev, cx_prev, cy_prev = hist[-2]
        t_now, cx_now, cy_now = hist[-1]
        dt = max(1e-6, t_now - t_prev)
        return ((cx_now - cx_prev) ** 2 + (cy_now - cy_prev) ** 2) ** 0.5 / dt
